name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - name: Run tests
      run: echo "add pytest here later"

  deploy:
    needs: build-test   # 🔥 THIS is the dependency rule
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
